CustomerManagement.WebApp/Controllers/CMUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CustomerManagement.Entities;
using CustomerManagement.WebApp.Models;
using CustomerManagement.BusinessLayer;
using CustomerManagement.BusinessLayer.Results;
using CustomerManagement.Entities.ModelView;
using CustomerManagement.WebApp.Filters;

namespace CustomerManagement.WebApp.Controllers
{
    [Exc]
    public class CMUserController : Controller
    {
        private CMUserManager cmUserManager = new CMUserManager();

        public ActionResult Index()
        {
            return View(cmUserManager.List());
        }

        public ActionResult Details(Guid activateGuid)
        {
            if (activateGuid == null || activateGuid == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMUser cMUser = cmUserManager.Find(x => x.ActivateGuid == activateGuid);
            if (cMUser == null)
            {
                return HttpNotFound();
            }
            return View(cMUser);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CMUser cMUser)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");

            if (ModelState.IsValid)
            {
                BusinessLayerResult<CMUser> res = cmUserManager.RegisterUser(cMUser);

                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return RedirectToAction("Index");
                }
            }

            return View(cMUser);
        }

        public ActionResult Edit(Guid activateGuid)
        {
            if (activateGuid == null || activateGuid == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMUser cMUser = cmUserManager.Find(x => x.ActivateGuid == activateGuid);
            if (cMUser == null)
            {
                return HttpNotFound();
            }
            return View(cMUser);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(CMUser cMUser, HttpPostedFileBase ProfileImage)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");
            if (ModelState.IsValid)
            {
                if (ProfileImage != null &&
                    (ProfileImage.ContentType == "image/jpeg" ||
                    ProfileImage.ContentType == "image/jpg" ||
                    ProfileImage.ContentType == "image/png"))
                {
                    string filename = $"user_{cMUser.ActivateGuid}.{ProfileImage.ContentType.Split('/')[1]}";

                    ProfileImage.SaveAs(Server.MapPath($"~/Image/{filename}"));
                    cMUser.ProfileImageFilename = filename;
                }

                BusinessLayerResult<CMUser> res = cmUserManager.UpdateProfile(cMUser);

                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return RedirectToAction("Index");
                }

                // Profil güncellendiği için session güncellendi.
                CurrentSession.Set<CMUser>("login", res.Result);

                return RedirectToAction("Details", new { activateGuid = res.Result.ActivateGuid });
            }

            return View(cMUser);
        }

        public ActionResult Delete(Guid activateGuid)
        {
            if (activateGuid == null || activateGuid == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMUser cMUser = cmUserManager.Find(x => x.ActivateGuid == activateGuid);
            if (cMUser == null)
            {
                return HttpNotFound();
            }
            return View(cMUser);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid activateGuid)
        {
            if (activateGuid == null || activateGuid == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMUser cMUser = cmUserManager.Find(x => x.ActivateGuid == activateGuid);
            cmUserManager.Delete(cMUser);
            return RedirectToAction("Index");
        }

        public ActionResult UserActivate(Guid id)
        {
            ActivationViewModal<string> activationViewModal = new ActivationViewModal<string>();
            BusinessLayerResult<CMUser> res = cmUserManager.ActivateUser(id);

            if (res.Errors.Count > 0)
            {
                activationViewModal.Title = "Etkinleştirme Hatası";
                res.Errors.ForEach(x => activationViewModal.Items.Add(x.Message));

                ViewBag.Result = res.Errors;
                return View(activationViewModal);
            }

            return View(activationViewModal);
        }

        public ActionResult Logout()
        {
            Session.Clear();

            return RedirectToAction("Index", "Home");
        }

    }
}

CustomerManagement.WebApp/Views/CMUser/Create.cshtml
@model CustomerManagement.Entities.CMUser

@{
    ViewBag.Title = "Kullanıcı Oluşturma";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@ViewBag.Title </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAdmin)
                    @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="card bg-primary text-white shadow" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

CustomerManagement.WebApp/Views/CMUser/Delete.cshtml
@model CustomerManagement.Entities.CMUser

@{
    ViewBag.Title = "Kullanıcı Sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kullanıcı kaydını silmek istediğinize emin misiniz?</h3>
<div>
    <h4>@ViewBag.Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        @Html.HiddenFor(model => model.ActivateGuid)
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <div class="row">
                <div class="col-lg-1">
                    <div class="card bg-primary text-white shadow">
                        <button class="card bg-primary text-white shadow" type="submit">Sil</button>
                    </div>
                </div>
                <div class="col-xs-1">|</div>
                <div class="col-lg-1">@Html.ActionLink("Listeye Geri Dön", "Index")</div>
            </div>
        </div>
    }
</div>

CustomerManagement.WebApp/Views/CMUser/Details.cshtml
@model CustomerManagement.Entities.CMUser

@{
    ViewBag.Title = "Kullanıcı Detayları";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h3>@ViewBag.Title</h3>
        <hr />
    </div>
    <div class="row">
        <div class="col-md-2">
            <img src="~/Image/@Model.ProfileImageFilename" class="img-circle" width="128" height="128" />
        </div>
        <div class="col-md-10">
            <h5>@Model.Fullname</h5>
            <br />
            <h6><b>@Html.DisplayNameFor(model => model.Name) : </b>@Model.Name</h6>
            <h6><b>@Html.DisplayNameFor(model => model.Surname) : </b>@Model.Surname</h6>
            <h6><b>@Html.DisplayNameFor(model => model.Email) : </b>@Model.Email</h6>
            <h6><b>@Html.DisplayNameFor(model => model.Password) : </b>@Model.Password</h6>
            <h6><b>@Html.DisplayNameFor(model => model.IsActive) : </b>@Model.IsActive</h6>
            <h6><b>@Html.DisplayNameFor(model => model.IsActive) : </b>@Model.IsActive</h6>
            @Html.HiddenFor(model => model.ActivateGuid)
            <br />
        </div>
    </div>
    <div class="row">
        <p>
            @Html.ActionLink("Düzenle", "Edit", new { activateGuid = Model.ActivateGuid })  |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </p>
    </div>
</div>

CustomerManagement.WebApp/Views/CMUser/Edit.cshtml
@using CustomerManagement.Entities
@model CMUser

@{
    ViewBag.Title = "Kullanıcı Bilgisi Düzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.AntiForgeryToken()

<div class="container-fluid">
    <h4>@ViewBag.Title</h4>
    <hr />

    <div>
        @using (Html.BeginForm("Edit", "CMUser", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.ActivateGuid)
            <div class="row">
                <div class="col-md-3">
                    <img src="~/Image/@Model.ProfileImageFilename" class="img-circle" width="128" height="128" />
                    @Html.HiddenFor(model => model.ProfileImageFilename)
                    <br /><br />
                    <input type="file" name="ProfileImage" id="ProfileImage" class="form-control" /><br />
                    <span class="glyphicon glyphicon-info-sign">&nbsp;</span>
                    <span><i>Lütfen jpg, jpeg ya da png formatı kullanın.</i></span>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsAdmin)
                                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2 mb-4">
                            <div class="card bg-primary text-white shadow">
                                <button class="card bg-primary text-white shadow" type="submit"><span style="text-align:center">Güncelle</span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

CustomerManagement.WebApp/Views/CMUser/Index.cshtml
@model IEnumerable<CustomerManagement.Entities.CMUser>

@{
    ViewBag.Title = "Kullanıcı Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Kullanıcı Oluştur", "Create")
</p>

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kategori Listesi</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Surname)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Password)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsAdmin)
                            </th>
                            <th width="15%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            @Html.HiddenFor(model => item.ActivateGuid)
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Surname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Password)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsActive)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsAdmin)
                                </td>
                                <td>
                                    @Html.ActionLink("Düzenle", "Edit", new { activateGuid = item.ActivateGuid }) |
                                    @Html.ActionLink("Detaylar", "Details", new { activateGuid = item.ActivateGuid }) |
                                    @Html.ActionLink("Sil", "Delete", new { activateGuid = item.ActivateGuid })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

CustomerManagement.WebApp/Views/CMUser/UserActivate.cshtml
@using CustomerManagement.Entities.ModelView
@model ActivationViewModal<string>
@{
    ViewBag.Title = "UserActivate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
@*<h2>Kullanıcı Etkinleştirme</h2>*@

<div class="container">
    <div class="card  text-center">
        <div class="card-header">
            @Model.Header
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <h5 class="card-title">@Model.Title</h5>
                @if (Model.Items != null && Model.Items.Count > 0)
            {
                foreach (var item in Model.Items)
                {
                        <p class="card-text">item</p>
                    }
                }
            </blockquote>
        </div>
    </div>
</div>
@{
    string js = string.Empty;

    if (Model.IsRedirecting)
    {
        js = "setTimeout(function () { window.location = '" + Model.RedirectingUrl + "'; }, " +
     Model.RedirectingTimeout + ");";
    }
}
<script>

    $(function () {
        @Html.Raw(js);
    });

</script>